### ISSUE TITLE
Building for UWP

### ISSUE THREAD

**Issue by Noemata** [FrayxRulez/webrtc-uwp#1]
How are you building the m91 branch for UWP?

**Comment by FrayxRulez** [comment]
Hi! Keep in mind that this repository actually contains some changes specific to Telegram, specifically:
- [api/peer_connection_interface.h](https://github.com/FrayxRulez/webrtc-uwp/commit/0ce34d1dcbe761f63fa3f5f2b8fa3b09710bf4df#diff-f85b907b9bd399086f65979d5eb552921302eb35d005f1b325d6e62ec5dcda3f)
- [audio/audio_state.h](https://github.com/FrayxRulez/webrtc-uwp/commit/0ce34d1dcbe761f63fa3f5f2b8fa3b09710bf4df#diff-a93bfe6407755e555c5e412fe36037f94851b2cae526cc8dc0f8704e6c6d7511)
- [media/engine/webrtc_media_engine.h](https://github.com/FrayxRulez/webrtc-uwp/commit/0ce34d1dcbe761f63fa3f5f2b8fa3b09710bf4df#diff-241a031088b0625136c0c35ab2748f1df8e15a92d343e820f283eb35f4c03507)
- [media/engine/webrtc_media_engine.h](https://github.com/FrayxRulez/webrtc-uwp/commit/0ce34d1dcbe761f63fa3f5f2b8fa3b09710bf4df#diff-d6bf448799b3428bb4dde62738cbd3dd7f1999eda71545cd07020235d7006fa0)
- [media/engine/webrtc_voice_engine.cc](https://github.com/FrayxRulez/webrtc-uwp/commit/0ce34d1dcbe761f63fa3f5f2b8fa3b09710bf4df#diff-56f5e0c459b287281ef3b0431d3f4129e8e4be4c6955d845bcb22210f08b7ba5)
- [media/engine/webrtc_voice_engine.h](https://github.com/FrayxRulez/webrtc-uwp/commit/0ce34d1dcbe761f63fa3f5f2b8fa3b09710bf4df#diff-427ab3f20c34f3c1ef23b67c81655babd45968d30804b7c9ccdeb63ef046b3f9)
- [pc/rtp_transport.cc](https://github.com/FrayxRulez/webrtc-uwp/commit/0ce34d1dcbe761f63fa3f5f2b8fa3b09710bf4df#diff-9902a2acf9c029784e81d85a46a27898ac26754a39d7924c97513f956260d28f)
- [pc/rtp_transport_internal.h](https://github.com/FrayxRulez/webrtc-uwp/commit/0ce34d1dcbe761f63fa3f5f2b8fa3b09710bf4df#diff-8e49f9886a8bfbb8b648d7751a0542cfb7fc002173da3220895a6738757d140a)

This shouldn't make a big difference, as the code mostly adds some callbacks around.

To actually compile you must follow [all the steps here](https://github.com/microsoft/winrtc/tree/master/patches_for_WebRTC_org/m84) apart from `Applying the patches`.

**Comment by Noemata** [comment]
Thanks for that.  What backend are you connecting to?
